/* System headers */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Custom headers */
#include <y.tab.h>
#include <lexer3.h>
#include <symtab.h>

/*
 * We need yylex_destroy or valgrind complains of memory leaks. When testing on
 * Ubuntu 8.04.2, Flex 2.5.34 was found to omit the yylex_destroy declaration
 * in the generated header file. Try to handle this case gracefully.
 */
#if YY_FLEX_MAJOR_VERSION == 2 \
    && YY_FLEX_MINOR_VERSION == 5 \
    && YY_FLEX_SUBMINOR_VERSION < 35
int yylex_destroy (void);
#endif

int yyparse (void);
#ifdef YYDEBUG
extern int yydebug;
#endif

int
main (int argc, char *argv[])
{
    int parse_rv;
#ifdef YYDEBUG
    yydebug = 1;
#endif

    if (argc > 1)
    {
        yyin = fopen (argv[1], "r");
        assert (NULL != yyin);
    }

    init_sym_table ();

    parse_rv = yyparse ();

    if (0 == parse_rv)
        printf ("Parsing completed. No errors found.\n");
    else
        printf ("Parsing aborted due to unrecoverable error(s).\n");

    if (argc > 1)
    {
        assert (0 == fclose (yyin));
    }

    destroy_sym_table ();

    /*
     * Not precisely as indicated by the manual, but seems to be the right
     * thing to do based on the C code generated by flex.
     */
    yylex_destroy ();

    /*
     * Successful exit code even if parsing failed. Unit test script depends
     * on this behavior.
     */
    exit (EXIT_SUCCESS);
}


int
yyerror (char const *mesg)
{
    printf ("%s\t%d\t%s\n", "Error found in Line ", yylineno,
            mesg);
    return 1;
}
