CC=gcc
CFLAGS=-g -Werror -pedantic-errors -ansi
# add -d to the next line to generate a debugging scanner
LEX=flex

# uses implicit rules to compile the scanner
scan:

.PHONY: clean

clean:
	$(RM) *.o scan
