/* System headers */
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Custom headers */
#include <y.tab.h>
#include <lexer4.h>
#include <header.h>

/*
 * We need yylex_destroy or valgrind complains of memory leaks. When testing on
 * Ubuntu 8.04.2, Flex 2.5.34 was found to omit the yylex_destroy declaration
 * in the generated header file. Try to handle this case gracefully.
 */
#if YY_FLEX_MAJOR_VERSION == 2 \
    && YY_FLEX_MINOR_VERSION == 5 \
    && YY_FLEX_SUBMINOR_VERSION < 35
int yylex_destroy (void);
#endif

int yyparse (void);
#ifdef YYDEBUG
extern int yydebug;
#endif
extern int ISERROR;
extern int linenumber;

int
main (int argc, char *argv[])
{
#ifdef YYDEBUG
    yydebug = 1;
#endif

    if (argc > 1)
    {
        yyin = fopen (argv[1], "r");
        assert (NULL != yyin);
    }

    ISERROR = 0;
    put_read_ST ();
    yyparse ();

    if (0 == ISERROR)
        printf ("Parsing completed. No errors found.\n");
    else
    {
        if (argc > 1)
            printf ("Errors found in file %s\n", argv[1]);
        else
            printf ("Errors found in file -stdin-\n");
    }

    if (argc > 1)
    {
        assert (0 == fclose (yyin));
    }

    /*
     * Not precisely as indicated by the manual, but seems to be the right
     * thing to do based on the C code generated by flex.
     */
    yylex_destroy ();

    /*
     * Successful exit code even if parsing failed. Unit test script depends
     * on this behavior.
     */
    exit (EXIT_SUCCESS);
}

int
yyerror (char *mesg)
{
    printf ("%s\t%d\t%s\t%s\n", "Error found in Line ", linenumber,
            "next token: ", yytext);
    exit (1);
}

/*
vim: expandtab shiftwidth=4 tabstop=4 smarttab
*/
